# Generated by Django 5.0.6 on 2024-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_purpose', models.CharField(max_length=50)),
                ('other_purpose_specify', models.CharField(blank=True, max_length=100)),
                ('business_description', models.TextField()),
                ('existing_website_url', models.URLField(blank=True)),
                ('primary_colors', models.CharField(blank=True, max_length=100)),
                ('fonts_typography', models.CharField(blank=True, max_length=100)),
                ('website_examples', models.TextField(blank=True)),
                ('existing_content', models.BooleanField(default=False)),
                ('content_creation_services', models.BooleanField(default=False)),
                ('pages_needed', models.TextField(blank=True)),
                ('features_needed', models.TextField(blank=True)),
                ('other_features_specify', models.CharField(blank=True, max_length=100)),
                ('integrations_needed', models.CharField(blank=True, max_length=100)),
                ('seo_services', models.BooleanField(default=False)),
                ('keywords_phrases', models.CharField(blank=True, max_length=100)),
                ('online_marketing', models.BooleanField(default=False)),
                ('domain_hosting', models.BooleanField(default=False)),
                ('setup_assistance', models.BooleanField(default=False)),
                ('cms_preference', models.CharField(blank=True, max_length=100)),
                ('maintenance_updates', models.BooleanField(default=False)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('additional_information', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
