# requirement_app/models.py
from django.db import models

class WebsiteRequirement(models.Model):
    client_name = models.CharField(max_length=100)
    company_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    website_purpose = models.CharField(max_length=50)
    other_purpose_specify = models.CharField(max_length=100, blank=True)
    business_description = models.TextField()
    existing_website_url = models.URLField(blank=True)
    primary_colors = models.CharField(max_length=100, blank=True)
    fonts_typography = models.CharField(max_length=100, blank=True)
    website_examples = models.TextField(blank=True)
    existing_content = models.BooleanField(default=False)
    content_creation_services = models.BooleanField(default=False)
    pages_needed = models.TextField(blank=True)
    features_needed = models.TextField(blank=True)
    other_features_specify = models.CharField(max_length=100, blank=True)
    integrations_needed = models.CharField(max_length=100, blank=True)
    seo_services = models.BooleanField(default=False)
    keywords_phrases = models.CharField(max_length=100, blank=True)
    online_marketing = models.BooleanField(default=False)
    domain_hosting = models.BooleanField(default=False)
    setup_assistance = models.BooleanField(default=False)
    cms_preference = models.CharField(max_length=100, blank=True)
    maintenance_updates = models.BooleanField(default=False)
    launch_date = models.DateField(blank=True, null=True)
    budget_range = models.CharField(max_length=100, blank=True)
    additional_information = models.TextField(blank=True)
    submitted_at = models.DateTimeField(auto_now_add=True)
